### ISSUE TITLE
fwd: bug report from https://github.com/NVIDIA/NeMo/discussions/8076

### ISSUE THREAD

**Issue by XuesongYang** [NVIDIA/NeMo-text-processing#135]
I guess this potential bug is related to text normalization in this repo. please have a look.

ref: https://github.com/NVIDIA/NeMo/discussions/8076

**Comment by ekmb** [comment]
@mgrafu could you please take a look? cc @elenaltz

**Comment by rodrigoGA** [comment]
I have added a comment in the forum discussion.
The issue seems to be with the inverse normalizer inverse_normalization_es_us, which was the only one published for Spanish as of the issue date.
A few weeks ago, a new normalizer model was released on NGC that works correctly.
I want to clarify that it's a different model, not a corrected version; the inverse_normalization_es_us model still has the same issue.
Right now, I'm getting a 404 error (I assume the site is under maintenance), so I can't add links.
Thank you very much.
